stages:
  - lint
  - test

# Linting

lint-pylint:
  stage: lint
  image: python:3.10-slim
  script:
    # Install packages
    - python -m pip install -r requirements.txt
    # Run pylint
    - python -m pylint .

# Testing

test-pytest:
  stage: test
  image: python:latest
  script:
    # Install packages
    - python -m pip install -r requirements.txt
    # Run pytest
    - python -m pytest --junitxml=testlog.xml
  artifacts:
      paths:
          - testlog.xml
      reports:
          junit: testlog.xml
